#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export TERMINAL=urxvt
alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
alias blackice="~/Games/Black_Ice"
alias monitorfix="~/scripts/monitorfix.sh"
alias update_discord="exec ~/scripts/discordinstall.sh"
alias easymusic="exec ~/scripts/easymusic.sh"
alias packagelist="exec ~/scripts/packagelist.sh"
