#!/bin/sh
mocp -i | grep File | sed -e 's_File:__' -e 's:/home/sunderkeenin/Music/::' -e 's:/ssd/Music/::' -e 's:-: :g' -e's:_: :g' -e 's:.opus::' -e 's:.mp3::' -e 's:.m4a::' -e 's:.ogg::' > /home/sunderkeenin/configs/home/scripts/i3blocks/currentsong.txt
tail -n 1 /home/sunderkeenin/configs/home/scripts/i3blocks/currentsong.txt | sed -e 's:     : :g' -e 's:    : :g' -e 's:   : :g' -e 's:  : :'

